CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(128) NOT NULL,
	`title` varchar(256) NOT NULL,
	`excerpt` text,
	`content` text NOT NULL,
	`featuredImage` text,
	`author` varchar(128) NOT NULL DEFAULT 'Rose City Stays',
	`category` varchar(64) NOT NULL DEFAULT 'Tyler, TX',
	`tags` text,
	`metaDescription` varchar(320),
	`readTime` int NOT NULL DEFAULT 5,
	`published` int NOT NULL DEFAULT 1,
	`aiGenerated` int NOT NULL DEFAULT 0,
	`newsContext` text,
	`publishedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
