CREATE TABLE `manual_booking_links` (
	`id` int AUTO_INCREMENT NOT NULL,
	`token` varchar(64) NOT NULL,
	`propertySlug` varchar(64) NOT NULL,
	`propertyName` varchar(256) NOT NULL,
	`hostawayListingId` int,
	`checkIn` bigint NOT NULL,
	`checkOut` bigint NOT NULL,
	`nights` int NOT NULL,
	`guestCount` int NOT NULL DEFAULT 1,
	`nightlyRate` decimal(10,2) NOT NULL,
	`cleaningFee` decimal(10,2) NOT NULL DEFAULT '0',
	`discountAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`extraGuestFee` decimal(10,2) NOT NULL DEFAULT '0',
	`taxAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`totalAmount` decimal(10,2) NOT NULL,
	`bypassCameraDisclosure` int NOT NULL DEFAULT 0,
	`bypassGuestCount` int NOT NULL DEFAULT 0,
	`bypassTermsAcceptance` int NOT NULL DEFAULT 0,
	`bypassIdUpload` int NOT NULL DEFAULT 0,
	`adminNotes` text,
	`guestName` varchar(256),
	`guestEmail` varchar(320),
	`status` enum('active','paid','expired','revoked') NOT NULL DEFAULT 'active',
	`expiresAt` bigint NOT NULL,
	`stripeCheckoutSessionId` varchar(256),
	`hostawayReservationId` varchar(64),
	`bookingId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `manual_booking_links_id` PRIMARY KEY(`id`),
	CONSTRAINT `manual_booking_links_token_unique` UNIQUE(`token`)
);
